import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{LayoutDashboard,ChartCandlestick,Layers3,Bot,FlaskConical,Radio,History,Settings}from'lucide-react';
import'./styles.css';

const nav=[['Dashboard',LayoutDashboard],['Live Chart',ChartCandlestick],['Option Chain',Layers3],['Price Ladder',Layers3],['Factor-J AI',Bot],['Paper Trading',FlaskConical],['Live Trading',Radio],['Trade History',History],['Settings',Settings]];
const fallback=[24812.95,24812.90,24812.85,24812.80,24812.75,24812.70,24812.65,24812.60,24812.55,24812.50,24812.45,24812.40,24812.35];
function App(){
 const[page,setPage]=useState('Dashboard'),[limit,setLimit]=useState('24812.65'),[side,setSide]=useState(''),[ladder,setLadder]=useState(fallback),[indices,setIndices]=useState([]),[signal,setSignal]=useState(null),[api,setApi]=useState(false);
 useEffect(()=>{Promise.all([fetch('http://localhost:8000/api/health').then(r=>r.json()),fetch('http://localhost:8000/api/market/summary').then(r=>r.json()),fetch('http://localhost:8000/api/market/ladder').then(r=>r.json()),fetch('http://localhost:8000/api/factor-j/signal').then(r=>r.json())]).then(([h,m,l,s])=>{setApi(h.ok);setIndices(m.indices);setLadder(l.rows);setSignal(s)}).catch(()=>{})},[]);
 const pick=(p,s='')=>{setLimit(Number(p).toFixed(2));if(s)setSide(s)};
 return <div className="app"><aside><div className="brand"><b>OPTION <i>BAZAAR</i></b><small>Powered by Factor-J AI</small></div><nav>{nav.map(([n,I])=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}><I size={16}/><span>{n}</span></button>)}</nav><div className="broker"><small>Broker</small><b>FYERS</b><em>NOT CONNECTED</em></div></aside><main><header>{(indices.length?indices:[{symbol:'NIFTY 50',ltp:24812.65,change_pct:.62},{symbol:'BANK NIFTY',ltp:51236.9,change_pct:.41},{symbol:'INDIA VIX',ltp:12.45,change_pct:-2.51}]).map(x=><div className="ticker" key={x.symbol}><small>{x.symbol}</small><b>{x.ltp.toLocaleString()}</b><span className={x.change_pct>=0?'pos':'neg'}>{x.change_pct>0?'+':''}{x.change_pct}%</span></div>)}<div className="status">● {api?'BACKEND READY':'TEST PREVIEW'} &nbsp; ● PAPER</div></header>{page==='Dashboard'?<Dashboard ladder={ladder} limit={limit} setLimit={setLimit} pick={pick} side={side} signal={signal}/>:<Placeholder page={page}/>}</main></div>
}
function Dashboard({ladder,limit,setLimit,pick,side,signal}){return <div className="content"><div className="upper"><section className="panel chartPanel"><div className="toolbar"><div><button className="sel">NIFTY 50</button><button>BANK NIFTY</button><button>FINNIFTY</button></div><div><button>5s</button><button>1m</button><button className="sel">5m</button><button>Indicators ▾</button></div></div><div className="chart"><div className="test">TEST DATA</div>{Array.from({length:54},(_,i)=><span key={i} className={'candle '+(i%3?'up':'down')} style={{left:24+i*15,top:55+(i*31)%250,height:24+(i*17)%70}}/>)}<div className="trade tp">TP 24,950 &nbsp; +₹8,925</div><div className="trade entry">ENTRY 24,812.65 &nbsp; ₹0</div><div className="trade sl">SL 24,700 &nbsp; -₹7,322</div></div><div className="indicators"><span>Volume <b>2.153M</b></span><span>RSI 14 <b>58.21</b></span><span>Supertrend <b className="pos">Bullish</b></span></div></section><div className="right"><section className="panel"><h3>Price Ladder <small>TEST DATA</small></h3><div className="lh"><span>BUY</span><span>PRICE</span><span>SELL</span></div>{ladder.slice(0,13).map(p=><div className="lr" key={p}><button className="buy" onClick={()=>pick(p,'BUY')}>BUY</button><button className={'price '+(Number(limit)===Number(p)?'chosen':'')} onClick={()=>pick(p)}>{Number(p).toFixed(2)}</button><button className="sell" onClick={()=>pick(p,'SELL')}>SELL</button></div>)}</section><section className="panel order"><h3>Quick Order <small>{side||'PAPER'}</small></h3><label>Symbol<select><option>NIFTY</option></select></label><div className="cols"><label>Lots<input defaultValue="1"/></label><label>Lot Size<input defaultValue="65"/></label></div><label>Total Qty<input defaultValue="65"/></label><label>Order Type<select><option>LIMIT</option><option>MARKET</option></select></label><label>Limit Price<input value={limit} onChange={e=>setLimit(e.target.value)}/></label><div className="actions"><button className="buyMain">BUY CALL</button><button className="sellMain">BUY PUT</button></div></section></div></div><div className="lower"><section className="panel"><h3>Positions <small>PAPER</small></h3><table><tbody><tr><th>Symbol</th><th>Qty</th><th>Avg</th><th>LTP</th><th>P&L</th></tr><tr><td>NIFTY 24800 CE</td><td>65</td><td>115.20</td><td>122.80</td><td className="pos">+₹494</td></tr></tbody></table></section><section className="panel"><h3>Factor-J Signal <small>TEST DATA</small></h3><div className="signal">{signal?.signal||'STRONG BUY'} — {signal?.confidence||78}%</div><p>Trend: <span className="pos">{signal?.trend||'Bullish'}</span><br/>Risk/Reward: 1:{signal?.risk_reward||2.35}</p></section><section className="panel"><h3>Recent Trades</h3><p className="mono">10:10:15 NIFTY 24800 CE <span className="pos">+₹7,325</span><br/>09:45:30 NIFTY 24750 PE <span className="pos">+₹2,105</span><br/>09:30:22 NIFTY 24800 CE <span className="neg">-₹1,485</span></p></section></div></div>}
function Placeholder({page}){return <div className="content"><section className="panel placeholder"><h2>{page}</h2><p>This page is part of the shared Option Bazaar build. Dashboard is the first active implementation; this page will be connected and tested next.</p><span>DEVELOPMENT / TEST ENVIRONMENT</span></section></div>}
createRoot(document.getElementById('root')).render(<App/>);
